const CONSTANTS = {
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    SORT_BRAND_LIST:'SORT_BRAND_LIST',
    VIEW_ALL_BRANDS_LIST: 'VIEW_ALL_BRANDS_LIST',
    FULL_DELETE_FROM_CART: 'FULL_DELETE_FROM_CART'
}

export default CONSTANTS